- name: Get time from the local machine
  local_action: ansible.builtin.command date +%y%m%d-%H:%M
  changed_when: false
  register: _controller_time_
  run_once:  yes
  when: master==1

- name: Set backup_time fact
  set_fact:
    backup_time : "{{ _controller_time_ }}"

- name: Dump all databases to hostname.sql including master data
  community.mysql.mysql_db:
    state: dump
    name: all
    target: /tmp/{{ backup_time }}.sql
    master_data: 1
    login_unix_socket: /var/run/mysqld/mysqld.sock
  when: master==1

- name: fetch mysql_backup
  fetch:
    src: /tmp/{{ backup_time }}.sql
    dest: /home/cocafe/db_backups/{{ inventory_hostname }}_{{ backup_time }}.sql
  when: master==1

- name: oss sync
  become: yes
  become_user: cocafe
  local_action: ansible.builtin.command /usr/local/bin/ossutil64 sync /home/cocafe/db_backups oss://bucket-databases-backup/databases-backups
  run_once:  yes
  when: master==1

# - name: upload sentinel config file 
#   template:
#     dest: /etc/redis/sentinel.conf
#     src: sentinel.conf.j2
#     mode: 0640

# - name: restart redis
#   systemd:
#     state: restarted
#     daemon_reload: yes
#     name: redis

# - name: restart master redis
#   systemd:
#     state: restarted
#     daemon_reload: yes
#     name: redis
#   when: redis_master==1

# - name: restart slave redis
#   systemd:
#     state: restarted
#     daemon_reload: yes
#     name: redis
#   when: redis_master!=1

# - name: restart redis-sentinel
#   systemd:
#     state: restarted
#     daemon_reload: yes
#     name: redis-sentinel