---
service_ip_1: 172.26.1.132
service_ip_2: 172.26.1.131
service_port: 8080
server_domain_name: nfo.cocafe.co
project_name: nfo
non_www_domain_name: cocafe.co
www_domain_name: www.cocafe.co
www_project_name: www