-  name: update authorized_keys
   template:
      src: authorized_keys.j2
      dest: /home/cocafe/.ssh/authorized_keys
      owner: "{{ ssh_user_name }}"
      group: "{{ ssh_user_name }}"
      mode: 0700
      backup: yes
     