- name: remove password ssh method
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: "^PasswordAuthentication"
    line: "PasswordAuthentication no"
    insertafter: "^#PasswordAuthentication"

- name: upload limits.conf
  copy:
    src: files/limits.conf
    dest: '/etc/security/limits.conf'
    owner: root
    group: root
    mode: 0644

- name: flash limit arg
  shell: "ulimit -SHn 65536"

- name: apt install
  apt:
    name: 
      - 'git'
      - 'tree'
      - 'nodejs'
      - 'npm'
      - 'axel'
      - 'gettext'
      - 'jq'
      - 'libpq-dev'
      - 'apt-transport-https'
      - 'ca-certificates'
      - 'curl'
      - 'gnupg-agent'
      - 'software-properties-common'
      - 'pkg-config'
      - 'libssl-dev'
      - 'libaio1'
      - 'snapd'
    update_cache: true
    state: present



# - name: send go
#   copy: 
#     src: files/go1.16.7.linux-amd64.tar.gz
#     dest: '/root/go1.16.7.linux-amd64.tar.gz'
#     owner: root
#     group: root
#     mode: 0644

- name: get go
  become: yes
  become_user: cocafe
  shell: "wget https://golang.org/dl/go1.17.1.linux-amd64.tar.gz"

- name: install go
  shell: "rm -rf /usr/local/go && tar -C /usr/local -xzf /home/cocafe/go1.17.1.linux-amd64.tar.gz"

- name: add go path
  become: yes
  become_user: cocafe
  lineinfile: 
    line: export PATH=$PATH:/usr/local/go/bin
    regexp: '^PATH\=\$PATH\:\/usr\/local\/go\/bin'
    path: $HOME/.bashrc

- name: change kernel vm.overcommit_memory = 1
  lineinfile:
    line: vm.overcommit_memory = 1
    path: /etc/sysctl.conf

- name: apply sysctl changes
  shell: sysctl -p

- name: disable swap partition
  shell: swapoff -a

- name: remove swap partition from /etc/fstab
  lineinfile:
    regex: '^/swap.img'
    path: /etc/fstab
    state: absent

- name: upload git private key
  copy:
    src: cocafe_id_rsa
    dest: '/home/cocafe/.ssh/id_rsa'
    owner: cocafe
    group: cocafe
    mode: 0400

- name: add proxy
  become: yes
  become_user: cocafe
  lineinfile: 
    line: 'export http_proxy="http://172.16.0.224:7890" https_proxy="http://172.16.0.224:7890"'
    regexp: '^PATH\=\$PATH\:\/usr\/local\/go\/bin'
    path: $HOME/.bashrc
  tags:
    - science
