- name: apt install nginx
  apt:
    name: nginx
    update_cache: true
    state: present

- name: Read-write git checkout from github
  become: yes
  become_user: cocafe
  ansible.builtin.git:
    repo: git@github.com:cocafe-labs/mcd-frontend.git
    dest: /var/cocafe-output/mcd-frontend
    force: yes

- name: remove build
  file:
    path: /var/cocafe-output/mcd-frontend/build
    state: absent

- name: npm run build
  become: yes
  become_user: cocafe
  shell: "cd /var/cocafe-output/mcd-frontend && npm run build"

# - name: update website's nginx configuration
#   template:
#     src: mcd-test.j2
#     dest: /etc/nginx/sites-enabled/mcd-test
#     mode: 0755

- name: restart nginx
  systemd:
    name: nginx
    state: restarted

- name: snap update core
  community.general.snap:
    name: core
    state: present

- name: apt remove certbot
  apt:
    name: certbot
    state: absent

- name: snap install certbot
  community.general.snap:
    name: certbot
    classic: yes
    state: present

- name: create a /usr/bin/ symbol link for certbot
  file:
    src: /snap/bin/certbot
    dest: /usr/bin/certbot
    state: link

# - name: generate certification due to  nginx configuration
#   shell: 'certbot --nginx'
#   register: certout

# - name: show certbot's output
#   debug:
#     vars: certout.stdout