# - name: test if host in the changelist
#   debug:
#       msg: "{{ (changelist|select('match','ansible_hostname')) }}"

- name: upload netplan config
  template:
    src: "01-netcfg.yaml.j2"
    dest: /etc/netplan/01-netcfg.yaml
    owner: root
    group: root
    mode: '0644'
    # validate: "netplan try %s"
    backup: yes

- name: get new_ip
  shell: cat /etc/netplan/01-netcfg.yaml | grep "\/24$" | sed 's/^[[:space:]]*.-.//g' | cut -d '/' -f 1
  register: new_ip

- name: network reload prepare
  debug:
    msg: "System {{ ansible_hostname }} 's IP {{ ansible_default_ipv4.address }} will be replaced to {{ new_ip.stdout }}."
  when: 
    - ansible_default_ipv4.address != new_ip.stdout
    - new_ip.stdout != ''

- name: network reload
  shell: netplan apply
  when: 
    - ansible_default_ipv4.address != new_ip.stdout
    - new_ip.stdout != ''
